
let data=getData();
function needLogin(){return localStorage.getItem("onbuild_v4_login")==="1"}
function login(){if(adminPw.value!=="1234"){alert("비밀번호가 다릅니다.");return}localStorage.setItem("onbuild_v4_login","1");location.reload()}
function logout(){localStorage.removeItem("onbuild_v4_login");location.reload()}
function uploadToInput(file,inputId,previewId){if(!file)return;const r=new FileReader();r.onload=()=>{document.getElementById(inputId).value=r.result;if(previewId)document.getElementById(previewId).src=r.result};r.readAsDataURL(file)}
function saveText(){data.heroTitle=heroTitleInput.value;data.heroText=heroTextInput.value;data.phone=phoneInput.value;data.address=addressInput.value;setData(data);alert("저장되었습니다.")}
function saveHero(){data.images.hero=heroImageInput.value;setData(data);renderAdmin();alert("배너 저장 완료")}
function saveServices(){data.services.forEach((s,i)=>{s.title=document.getElementById("st"+i).value;s.text=document.getElementById("sx"+i).value;data.images.services[i]=document.getElementById("si"+i).value});setData(data);renderAdmin();alert("서비스 저장 완료")}
function saveCompare(){data.images.compare=data.images.compare.map((_,i)=>document.getElementById("ci"+i).value);setData(data);renderAdmin();alert("비교 이미지 저장 완료")}
function saveGallery(){data.images.gallery=data.images.gallery.map((_,i)=>document.getElementById("gi"+i).value);data.galleryTitles=data.galleryTitles.map((_,i)=>document.getElementById("gt"+i).value);setData(data);renderAdmin();alert("갤러리 저장 완료")}
function saveDetail(){for(let s=0;s<3;s++){data.images.detail[s]=data.images.detail[s].map((_,i)=>document.getElementById(`di${s}_${i}`).value)}setData(data);renderAdmin();alert("상세 이미지 저장 완료")}
function addGallery(){data.galleryTitles.push("새 시공사례");data.images.gallery.push("https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=1200");setData(data);renderAdmin()}
function resetAll(){if(confirm("전체 초기화할까요?")){localStorage.removeItem(STORE_KEY);location.reload()}}
function renderAdmin(){
 if(!needLogin()){document.body.innerHTML=`<div class="loginBox"><h2>온빌드 관리자 로그인</h2><p class="notice">초기 비밀번호: 1234</p><label>비밀번호</label><input type="password" id="adminPw"><br><br><button class="btn gold" onclick="login()">로그인</button><br><br><a href="index.html">홈페이지로 이동</a></div>`;return}
 document.body.innerHTML=`<div class="adminLayout"><aside class="side"><h2>ONBUILD 관리자</h2><a href="#basic">기본정보</a><a href="#hero">배너</a><a href="#services">서비스</a><a href="#compare">철거&원상복구</a><a href="#gallery">시공사례 20컷</a><a href="#detail">자세히보기 이미지</a><a href="index.html">홈페이지 보기</a><button onclick="logout()">로그아웃</button></aside><main class="mainAdmin">
 <section id="basic" class="panel"><h2>기본 정보</h2><label>메인 제목</label><textarea id="heroTitleInput">${data.heroTitle}</textarea><label>메인 설명</label><textarea id="heroTextInput">${data.heroText}</textarea><label>전화번호</label><input id="phoneInput" value="${data.phone}"><label>주소</label><input id="addressInput" value="${data.address}"><br><br><button class="btn gold" onclick="saveText()">저장</button></section>
 <section id="hero" class="panel"><h2>메인 배너</h2><img id="heroPrev" src="${data.images.hero}" style="height:220px;object-fit:cover;border-radius:12px"><label>이미지 주소</label><input id="heroImageInput" value="${data.images.hero}"><label>이미지 업로드</label><input type="file" accept="image/*" onchange="uploadToInput(this.files[0],'heroImageInput','heroPrev')"><br><br><button class="btn gold" onclick="saveHero()">배너 저장</button></section>
 <section id="services" class="panel"><h2>전문 서비스</h2><div class="editList">${data.services.map((s,i)=>`<div class="editItem"><img id="sp${i}" src="${data.images.services[i]}"><label>서비스명</label><input id="st${i}" value="${s.title}"><label>설명</label><textarea id="sx${i}">${s.text}</textarea><label>이미지 주소</label><input id="si${i}" value="${data.images.services[i]}"><label>업로드</label><input type="file" accept="image/*" onchange="uploadToInput(this.files[0],'si${i}','sp${i}')"></div>`).join("")}</div><br><button class="btn gold" onclick="saveServices()">서비스 저장</button></section>
 <section id="compare" class="panel"><h2>철거&원상복구 비교 이미지</h2><div class="editList">${data.images.compare.map((src,i)=>`<div class="editItem"><img id="cp${i}" src="${src}"><label>${["시공 전","철거 진행","철거 완료","원상복구 완료"][i]}</label><input id="ci${i}" value="${src}"><label>업로드</label><input type="file" accept="image/*" onchange="uploadToInput(this.files[0],'ci${i}','cp${i}')"></div>`).join("")}</div><br><button class="btn gold" onclick="saveCompare()">비교 이미지 저장</button></section>
 <section id="gallery" class="panel"><h2>시공사례 이미지</h2><button class="btn gray" onclick="addGallery()">사례 추가</button><div class="editList">${data.images.gallery.map((src,i)=>`<div class="editItem"><img id="gp${i}" src="${src}"><label>제목</label><input id="gt${i}" value="${data.galleryTitles[i]||""}"><label>이미지 주소</label><input id="gi${i}" value="${src}"><label>업로드</label><input type="file" accept="image/*" onchange="uploadToInput(this.files[0],'gi${i}','gp${i}')"></div>`).join("")}</div><br><button class="btn gold" onclick="saveGallery()">갤러리 저장</button></section>
 <section id="detail" class="panel"><h2>자세히보기 상세 이미지</h2>${data.images.detail.map((arr,s)=>`<h3>${data.services[s].title} 상세 이미지 10컷</h3><div class="editList">${arr.map((src,i)=>`<div class="editItem"><img id="dp${s}_${i}" src="${src}"><label>${i+1}번 이미지</label><input id="di${s}_${i}" value="${src}"><label>업로드</label><input type="file" accept="image/*" onchange="uploadToInput(this.files[0],'di${s}_${i}','dp${s}_${i}')"></div>`).join("")}</div>`).join("")}<br><button class="btn gold" onclick="saveDetail()">상세 이미지 저장</button></section>
 <section class="panel"><button class="btn dark" onclick="resetAll()">전체 초기화</button></section>
 </main></div>`;
}
document.addEventListener("DOMContentLoaded",renderAdmin);
